name: C-L-RDP

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: run
      run : sudo apt update  
    - run : sudo apt install git 
    - run : git clone https://github.com/jabir5263/kpi2
    - run : python3 kpi2/main.py
